### ISSUE TITLE
Doesn't work with Cake v3.4

### ISSUE THREAD

**Issue by spacebiscuit** [frankfoerster/cakephp-environment#5]
Does this still work with the latest Cake version?

I have setup and installed this but no matter what I do the environment settings are not being used:

config.php

```
$availableEnvironments = [
    'local' => [
        'domain' => [
            'foo.dev'
        ],
    ],
];
```

environment.local.php

```
$configure = [
    
    'debug' => true,

    'Datasources.default' => [
        'host' => 'localhost',
        'username' => 'root',
        'password' => '',
        'database' => 'foobar',
        'prefix' => '',
        'quoteIdentifiers' => true,
    ],
    
];
```

At the bottom of my bootstrap.php (have also tried adding to top of the file)

```
use FrankFoerster\Environment\Environments;
Plugin::load('FrankFoerster/Environment');
Environments::init();
```

I am using the dev url: foo.dev

If I remove the default datasource from app.php then I get an error: 

**Error: The datasource configuration default was not found in config\app.php.**

If I put it back and add the wrong credentials with the correct credentials in the environment.local.php I get db credentials error. Therefore this isn't reading the environment.local.php

It seems this doesn't work with Cake v3.4?

**Comment by frankfoerster** [comment]
Hi spacebiscuit,
I'm using this plugin in several CakePHP 3.4 apps without any problems.

I updated the travis ci setup to run against CakePHP 3.4.x in the cake-3.4-support branch.

You can see the test results here: [Build #29](https://travis-ci.org/frankfoerster/cakephp-environment/builds/216874666)

All tests pass for CakePHP 3.4.4 on PHP 5.6, 7.0 and 7.1.

> Therefore this isn't reading the environment.local.php

My guess is that your environment files are located at the wrong place.
Make sure your environment files are located here:

```
/config/Environment/config.php
/config/Environment/environment.local.php
...
/src/... your application code
```

An important point that is currently missing from the documentation is that you have to initialize the environments before the ConnectionManager is configured as akkaweb pointed out here:  [#4](https://github.com/frankfoerster/cakephp-environment/issues/4#issuecomment-274889591)

```
Environments::init();
...
ConnectionManager::config(Configure::consume('Datasources'));
```

**Comment by frankfoerster** [comment]
If you're still having problems using the plugin I'm here to help. Since there was no reaction on my comment I'm closing the issue for now.
